/* eslint-disable prettier/prettier */
export const siteMetadata = {
    title: ' LOVIE AURORA',
    author: 'Dev Abu Hasan',
    headerTitle: 'LOVIE AURORA FULL STACK WEBSITE',
    description: 'LOVIE AURORA E-COMMERCE created by DevAbuHasan',
    language: 'en',
    siteUrl: 'https://abu-next-commerce.vercel.app',
    // siteRepo: '',
    siteLogo: '/static/images/logoSingle/LOGO_ORANGE.png',
    image: '/static/images/logo/LOVIE AURORA LOGO ORANGE.png',
    socialBanner: '',
    email: '',
    github: '',
    twitter: '',
    facebook: '',
    youtube: '',
    linkedin: '',
    locale: 'en-US',
    analytics: {
        plausibleDataDomain: '',
        simpleAnalytics: false,
        googleAnalyticsId: '',
    },
    comment: {
        provider: 'giscus',
        giscusConfig: {
            repo: process.env.NEXT_PUBLIC_GISCUS_REPO,
            repositoryId: process.env.NEXT_PUBLIC_GISCUS_REPOSITORY_ID,
            category: process.env.NEXT_PUBLIC_GISCUS_CATEGORY,
            categoryId: process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID,
            mapping: 'pathname',
            reactions: '1',
            metadata: '0',
            theme: 'light',
            darkTheme: 'transparent_dark',
            themeURL: '',
        },
        utterancesConfig: {
            repo: process.env.NEXT_PUBLIC_UTTERANCES_REPO,
            issueTerm: '',
            label: '',
            theme: '',
            darkTheme: '',
        },
        disqus: {
            shortname: process.env.NEXT_PUBLIC_DISQUS_SHORTNAME,
        },
    },
}
