/* eslint-disable prettier/prettier */
export const siteMetadata = {
    title: ' Next__Commerce',
    author: 'Dev Abu Hasan',
    headerTitle: 'Dev Abu hasan Next js e commerce Website',
    description: 'A next js e commerce website created by dev abu hasan',
    language: 'en',
    siteUrl: 'https://abu-next-commerce.vercel.app',
    siteRepo: 'https://github.com/dev-abuhasan',
    // siteLogo: '/static/images/logo_purple.png',
    // image: '/static/images/logo_square_purple.png',
    socialBanner: '',
    email: 'dev.abuhasan@gmail.com',
    github: 'https://github.com/dev-abuhasan',
    twitter: 'https://twitter.com/dev-abuhasan',
    facebook: 'https://facebook.com/dev.abuhasan',
    youtube: 'https://youtube.com/c/dev.abuhasan',
    linkedin: 'https://www.linkedin.com/in/devabuhasan',
    locale: 'en-US',
    analytics: {
        plausibleDataDomain: '',
        simpleAnalytics: false,
        googleAnalyticsId: '',
    },
    comment: {
        provider: 'giscus',
        giscusConfig: {
            repo: process.env.NEXT_PUBLIC_GISCUS_REPO,
            repositoryId: process.env.NEXT_PUBLIC_GISCUS_REPOSITORY_ID,
            category: process.env.NEXT_PUBLIC_GISCUS_CATEGORY,
            categoryId: process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID,
            mapping: 'pathname',
            reactions: '1',
            metadata: '0',
            theme: 'light',
            darkTheme: 'transparent_dark',
            themeURL: '',
        },
        utterancesConfig: {
            repo: process.env.NEXT_PUBLIC_UTTERANCES_REPO,
            issueTerm: '',
            label: '',
            theme: '',
            darkTheme: '',
        },
        disqus: {
            shortname: process.env.NEXT_PUBLIC_DISQUS_SHORTNAME,
        },
    },
}
